name: Cloudflare Pages Action
description: Deploy your project to Cloudflare Pages with automatic project creation and setup custom domain (with support multiple domain)
author: Ade Hery Shopyan

branding: 
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  api-token:
    required: true
    description: "Set api token"
    type: string

  account-id:
    required: true
    description: "Set account id"
    type: string

  branch:
    required: true
    description: "Set branch"
    type: string

  production-branch:
    required: true
    description: "Set production branch"
    type: string

  build-directory:
    required: true
    description: "Set build directory"
    type: string

  package-manager:
    required: true
    description: "Set package manager"
    type: string

  project-name:
    required: true
    description: "Set project name"
    type: string

  custom-domains:
    required: false
    description: "Set custom domains"
    default: ""
    type: string

  working-directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

outputs:
  deployment-url:
    description: "Define deployment url"
    value: ${{ steps.url.outputs.deployment-url }}

  pages-url:
    description: "Define pages url"
    value: ${{ steps.url.outputs.pages-url }}

runs:
  using: composite
  steps:
    - name: Deploy
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        workingDirectory: ${{ inputs.working-directory }}
        apiToken: ${{ inputs.api-token }}
        accountId: ${{ inputs.account-id }}
        preCommands: wrangler pages project create ${{ inputs.project-name }} --production-branch=${{ inputs.production-branch }} || true
        command: pages deploy ${{ inputs.build-directory }} --project-name=${{ inputs.project-name }} --branch=${{ inputs.branch }} --commit-dirty=true
        packageManager: ${{ inputs.package-manager }}

    - name: Setup Custom Domains
      if: "${{ inputs.custom-domains != '' }}"
      uses: kitabisa/cloudflare-pages-action/tools/setup-custom-domains@v2
      with:
        api-token: ${{ inputs.api-token }}
        account-id: ${{ inputs.account-id }}
        branch: ${{ inputs.branch }}
        production-branch: ${{ inputs.production-branch }}
        project-name: ${{ inputs.project-name }}
        custom-domains: ${{ inputs.custom-domains }}
        deployment-url: ${{ steps.deploy.outputs.deployment-url }}

    - name: Get deployment url
      id: url
      shell: bash
      env:
        PAGES_URL: ${{ steps.deploy.outputs.deployment-url }}
      run: |
        if [ -n "${{ inputs.custom-domains }}" ]; then
          CUSTOM_DOMAIN_URL=$(echo "${{ inputs.custom-domains }}" | tr ',' '\n' | xargs -I {} echo "https://{}" | tr '\n' ', ' | sed 's/, $//')
        fi

        if [ -z "$CUSTOM_DOMAIN_URL" ]; then
          echo "pages-url=$PAGES_URL" >> $GITHUB_OUTPUT
          echo "deployment-url=$CUSTOM_DOMAIN_URL" >> $GITHUB_OUTPUT
          echo "Your deployment has been successful and can be accessed at $PAGES_URL"
          echo "or you can also access it at $CUSTOM_DOMAIN_URL"
        else
          echo "pages-url=$PAGES_URL" >> $GITHUB_OUTPUT
          echo "deployment-url=$PAGES_URL" >> $GITHUB_OUTPUT
          echo "Your deployment has been successful and can be accessed at $PAGES_URL"
        fi
