name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Setup jq
        if: steps.release.outputs.release_created == 'true'
        run: sudo apt-get install -y jq

      - name: Create major tag
        if: steps.release.outputs.release_created == 'true'
        run: |
          LATEST_VERSION=$(jq -r '.tag_name' < "${{ steps.release.outputs.release_notes_path }}")
          MAJOR_VERSION=$(echo $LATEST_VERSION | cut -d. -f1)
          git tag -f v$MAJOR_VERSION
          git push origin v$MAJOR_VERSION
