name: Setup Custom Domains
description: Setup Custom Domains

inputs:
  api-token:
    required: true
    description: "Set api token"
    type: string

  account-id:
    required: true
    description: "Set account id"
    type: string

  branch:
    required: true
    description: "Set branch"
    type: string

  production-branch:
    required: true
    description: "Set production branch"
    type: string

  project-name:
    required: true
    description: "Set project name"
    type: string

  custom-domains:
    required: true
    description: "Set custom domains"
    type: string

  deployment-url:
    required: true
    description: "Set deployment url"
    type: string

runs:
  using: composite
  steps:
    - name: Setup Custom Domains
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.account-id }}
        PROJECT_NAME: ${{ inputs.project-name }}
        DEPLOYMENT_URL: ${{ inputs.deployment-url }}
        BRANCH: ${{ inputs.branch }}
        PRODUCTION_BRANCH: ${{ inputs.production-branch }}
      run: |
        custom_domains=$(echo '${{ inputs.custom-domains }}' | tr -s ' ' ',')
        if [ -n "$custom_domains" ]; then
          curl -s https://publicsuffix.org/list/public_suffix_list.dat -o public_suffix_list.dat
          for domain in $(echo "$custom_domains" | tr ',' '\n'); do
            echo "=============================================================================="
            echo "Setup custom domain for $domain"
            echo "=============================================================================="
            echo "Get main domain ..."
            tld=""
            parts=($(echo "$domain" | tr '.' ' '))
            num_parts=${#parts[@]}
            for ((i=$num_parts-1; i>=1; i--)); do
              suffix=$(echo "${parts[@]:$i}" | tr ' ' '.')
              if grep -Fxq "$suffix" public_suffix_list.dat; then
                tld=$(echo "${parts[@]:$i}" | tr ' ' '.')
              fi
            done
            tld_parts=($(echo "$tld" | tr '.' ' '))
            tld_num_parts=${#tld_parts[@]}
            topdomain=$(echo "${parts[$i-$tld_num_parts-1]}.${tld}")

            if [ -n "$topdomain" ]; then
              echo "Main domain is $topdomain"
              echo "Get cloudflare zone for $topdomain ..."
              getzone=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${topdomain}" \
                -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                -H "Content-Type: application/json")
              zone_id=$(echo $getzone | jq -r '.result[0].id')
              
              if [ -n "$zone_id" ]; then
                echo "Cloudflare zone is found"
                echo "Get cloudflare dns record for $domain ..."
                getdns=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records?type=CNAME&name=${domain}" \
                  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                  -H "Content-Type: application/json")
                dns_record_id=$(echo $getdns | jq -r '.result[0].id')

                if [ -n "$dns_record_id" ]; then
                  echo "Cloudflare dns record is found"
                else
                  echo "Cloudflare dns record is not found"
                  echo "Setup dns record for $domain ..."
                  postdns=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records" \
                    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                    -H "Content-Type: application/json" \
                    --data '{
                      "type": "CNAME",
                      "name": "'"${domain}"'",
                      "content": "'"$PROJECT_NAME"'.pages.dev",
                      "ttl": 1,
                      "proxied": true
                    }')
                  dns_record_id=$(echo $postdns | jq -r '.result.id')

                  if [ -n "$dns_record_id" ]; then
                    echo "Cloudflare dns record is created"
                    echo "Setup custom domain for $PROJECT_NAME ..."
                    postcustomdomain=$(curl -s -X POST "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$PROJECT_NAME/domains" \
                      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                      -H "Content-Type: application/json" \
                      --data '{"name": "'${domain}'"}')
                    custom_domain_id=$(echo $postcustomdomain | jq -r '.result.id')

                    if [ -n "$custom_domain_id" ]; then
                      echo "Custom domain for $PROJECT_NAME is created"
                    fi
                  fi
                fi

                if [ "$BRANCH" != "$PRODUCTION_BRANCH" ]; then
                  echo "Update dns record for $domain ..."
                  deployment_url=$(echo "$DEPLOYMENT_URL" | sed 's/^https:\/\///')
                  patchdns=$(curl -s -X PATCH "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records/${dns_record_id}" \
                    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                    -H "Content-Type: application/json" \
                    --data '{
                      "type": "CNAME",
                      "name": "'"${domain}"'",
                      "content": "'"${deployment_url}"'",
                      "id": "'"${dns_record_id}"'",
                      "ttl": 1,
                      "proxied": true
                    }')
                  patch_dns_record_id=$(echo $patchdns | jq -r '.result.id')
                  
                  if [ -n "$patch_dns_record_id" ]; then
                    echo "Cloudflare dns record is updated"
                  fi
                fi
              fi
            fi
          done
          rm public_suffix_list.dat
        fi
